menu "Target"
bool ARCH_X86_64 "x86_64 support" y
endmenu

menu "Kernel"
bool ENABLE_SMP "Enable SMP" n
bool ENABLE_KPTI "Enable KPTI" y
bool ENABLE_ASLR "Enable ASLR" y
string KERNEL_RUST_TOOLCHAIN "Kernel Rust toolchain" "nightly-2026-05-14"
string USER_RUST_STD_TOOLCHAIN "User Rust std toolchain" "nightly"
endmenu

menu "Userland"
bool USER_BUILD_SELFTESTS "Build selftests" y
bool USER_BUILD_MPK_SAMPLES "Build MPK samples" y
endmenu

menu "Image"
string IMAGE_INITFS_SIZE_MB "Initial initfs size (MB)" "16"
string IMAGE_DISK_SIZE_MB "Initial disk size (MB)" "256"
string IMAGE_ESP_SIZE_MB "Initial ESP size (MB)" "128"
endmenu

menu "Drivers"
bool DRIVER_XHCI "Enable xHCI driver" n
bool DRIVER_I8042 "Enable i8042 driver" y
endmenu

menu "Debug"
bool DEBUG_QEMU_GUI "Enable QEMU GUI" y
bool DEBUG_QEMU_DEBUG "Enable QEMU debug mode" n
bool DEBUG_QEMU_KVM "Enable QEMU KVM acceleration" n
string DEBUG_QEMU_CPU "QEMU CPU model" "qemu64"
string DEBUG_QEMU_SMP "QEMU SMP CPU count" "1"
endmenu
