menu "Target"
bool CONFIG_ARCH_X86_64 "x86_64 support" y
endmenu

menu "Kernel"
bool CONFIG_ENABLE_SMP "Enable SMP" n
bool CONFIG_ENABLE_KPTI "Enable KPTI" y
bool CONFIG_ENABLE_ASLR "Enable ASLR" y
string CONFIG_KERNEL_TOOLCHAIN "Kernel toolchain" "nightly-2026-05-14"
string CONFIG_RUST_STD_TOOLCHAIN "Rust std toolchain" "nightly"
endmenu

menu "Userland"
bool CONFIG_BUILD_SELFTESTS "Build selftests" y
bool CONFIG_BUILD_MPK_SAMPLES "Build MPK samples" y
endmenu

menu "Image"
string CONFIG_INITFS_SIZE_MB "Initial initfs size (MB)" "16"
string CONFIG_DISK_SIZE_MB "Initial disk size (MB)" "256"
string CONFIG_ESP_SIZE_MB "Initial ESP size (MB)" "64"
endmenu
